#!/bin/bash

# https://docs.influxdata.com/influxdb/v1.8/query_language/explore-schema/

#set -x

INFLUX="docker exec -i influxdb influx --database telegraf -precision rfc3339"
MEASUREMENT="/network-instances/network-instance/protocols/protocol/bgp"


echo -e "\n===== Measurements ====="
$INFLUX <<EOM
SHOW MEASUREMENTS;
EOM

echo -e "\n===== TAG keys from Measurements ====="
$INFLUX <<EOM
SHOW TAG KEYS from "$MEASUREMENT";
EOM

echo -e "\n===== keys from neighbor-address ====="
$INFLUX <<EOM
SHOW TAG VALUES FROM "$MEASUREMENT" with KEY = "/network-instances/network-instance/@name";
SHOW TAG VALUES FROM "$MEASUREMENT" with KEY = "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/@neighbor-address";
SHOW TAG VALUES FROM "$MEASUREMENT" with KEY = "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/afi-safis/afi-safi/@afi-safi-name";
SHOW TAG VALUES FROM "$MEASUREMENT" with KEY = "/network-instances/network-instance/protocols/protocol/bgp/peer-groups/peer-group/@peer-group-name";
SHOW TAG VALUES FROM "$MEASUREMENT" with KEY = "/network-instances/network-instance/protocols/protocol/bgp/peer-groups/peer-group/afi-safis/afi-safi/@afi-safi-name";
EOM

echo -e "\n===== TAG keys from Measurements ====="
$INFLUX <<EOM
SHOW FIELD KEYS from "$MEASUREMENT";
EOM

echo -e "\n===== total-prefixes ====="
$INFLUX <<EOM
select "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/@neighbor-address","/network-instances/network-instance/protocols/protocol/bgp/global/state/total-prefixes" from "$MEASUREMENT";
EOM

#$INFLUX <<EOM
#select * from "$MEASUREMENT" limit 2;
#EOM



