#!/bin/bash

# https://docs.influxdata.com/influxdb/v1.8/query_language/explore-schema/
#/interfaces/interface[if_name='et-0/0/53']/state/error-counters/if_in_discards                             integer
#/interfaces/interface[if_name='et-0/0/53']/state/error-counters/if_in_errors                               integer
#/interfaces/interface[if_name='et-0/0/53']/state/error-counters/if_in_fifo_errors                          integer
#/interfaces/interface[if_name='et-0/0/53']/state/error-counters/if_in_frame_errors                         integer
#/interfaces/interface[if_name='et-0/0/53']/state/error-counters/if_in_l2_mismatch_timeouts                 integer
#/interfaces/interface[if_name='et-0/0/53']/state/error-counters/if_in_l2chan_errors                        integer
#/interfaces/interface[if_name='et-0/0/53']/state/error-counters/if_in_l3_incompletes                       integer
#/interfaces/interface[if_name='et-0/0/53']/state/error-counters/if_in_qdrops                               integer
#/interfaces/interface[if_name='et-0/0/53']/state/error-counters/if_in_resource_errors                      integer
#/interfaces/interface[if_name='et-0/0/53']/state/error-counters/if_in_runts                                integer
#/interfaces/interface[if_name='et-0/0/53']/state/error-counters/if_out_discards                            integer
#/interfaces/interface[if_name='et-0/0/53']/state/error-counters/if_out_errors

docker exec -i influxdb influx --database "telegraf" -precision "rfc3339" <<EOM

--select non_negative_derivative(mean("/interfaces/interface[if_name='et-0/0/51']/state/counters/if_in_octets"),1s) * 8 from "interfaces" where "device" = '10.48.188.97' and time >= now() - 10m GROUP BY time(5m) fill(none);

select non_negative_derivative(sum("/interfaces/interface[if_name='et-0/0/53']/state/error-counters/if_in_discards"),1s)
    from "interfaces" 
    where "device" = '10.48.188.97' and time >= now() - 10m 
    GROUP BY time(5m) fill(none);


EOM

