#!/bin/bash

# https://docs.influxdata.com/influxdb/v1.8/query_language/explore-schema/

docker exec -i influxdb influx --database "telegraf" -precision "rfc3339" <<EOM
-- SHOW RETENTION POLICIES;

-- SHOW MEASUREMENTS;

-- SHOW TAG KEYS;

-- SHOW TAG VALUES FROM "events" WITH KEY = "device";

--SHOW FIELD KEYS FROM "events";

--select * from events where "/junos/events/event/message" =~ /UI_COMMIT_COMPLETED/;

--select "/junos/events/event/message" from events limit 10;
-- 2021-04-28T00:29:43.141608796Z UI_COMMIT_COMPLETED:  : commit complete 

--select device,"/junos/events/event/message" from events where "/junos/events/event/@id" = 'UI_COMMIT_COMPLETED' and "device" = '10.161.35.118';

--select "/junos/events/event/message" from events where "/junos/events/event/@id" = 'UI_COMMIT_COMPLETED';

-- SHOW TAG VALUES FROM "events" with key = "device" where "/junos/events/event/@id" = 'UI_COMMIT_COMPLETED';

--select "/junos/events/event/message" from events;

-- select device,"/junos/events/event/message" from "events" where "/junos/events/event/@id" =~ /^RPD_BGP_NEIGHBOR_STATE_CHANGED|^BGP_RESET_PENDING_CONNECTION|^BGP_CONNECT_FAILED/

select device,"/junos/events/event/message" from "events" where "/junos/events/event/@id" =~ /^RPD_ISIS_ADJDOWN|^RPD_ISIS_ADJUP/


--select "/junos/events/event/message" from "events" 

EOM
