#!/bin/bash

# https://docs.influxdata.com/influxdb/v1.8/query_language/explore-schema/

interface="et-0/0/51"

docker exec -i influxdb influx --database "telegraf" -precision "rfc3339" <<EOM

--select "/interfaces/interface[if_name='et-0/0/51']/state/if_high_speed"
--select /"/interfaces/interface[if_name='et-*']/state/if_high_speed"/
--select "/interfaces/interface[if_name='$interface']/state/if_high_speed"
--  from "interfaces" 
--  where "device" = '10.48.188.97' limit 20
  
select "/interfaces/interface[if_name='et-0/0/48']/state/if_last_change"
  from "interfaces" 
  where "device" = '10.48.188.97' limit 20

EOM



# select derivative(mean("/interfaces/interface[if_name='et-0/0/51']/state/counters/if_in_octets"),1s) * 8 from "interfaces" where "device" = '10.48.188.97' and $timeFilter GROUP BY time($__interval) fill(none);


