#!/bin/bash

# https://docs.influxdata.com/influxdb/v1.8/query_language/explore-schema/

docker exec -i influxdb influx --database "telegraf" -precision "rfc3339" <<EOM


select max("/interfaces/interface[if_name='et-0/0/51']/state/counters/if_in_1sec_octets") from "interfaces"
   GROUP BY time(1m) fill(none);



EOM



# select derivative(mean("/interfaces/interface[if_name='et-0/0/51']/state/counters/if_in_octets"),1s) * 8 from "interfaces" where "device" = '10.48.188.97' and $timeFilter GROUP BY time($__interval) fill(none);


