#!/bin/bash

# https://docs.influxdata.com/influxdb/v1.8/query_language/explore-schema/

#set -x

INFLUX="docker exec -i influxdb influx --database telegraf -precision rfc3339"
MEASUREMENT="/network-instances/network-instance/protocols/protocol/isis"


echo -e "\n===== Measurements ====="
$INFLUX <<EOM
SHOW MEASUREMENTS;
EOM

echo -e "\n===== TAG keys from Measurements ====="
$INFLUX <<EOM
SHOW TAG KEYS from "$MEASUREMENT";
EOM

echo -e "\n===== tag values from measurements ====="
$INFLUX <<EOM
SHOW TAG VALUES FROM "$MEASUREMENT" with KEY IN (SHOW TAG KEYS from "$MEASUREMENT")
--SHOW TAG VALUES FROM "$MEASUREMENT" with KEY = "/components/component/properties/property/@name";
--SHOW TAG VALUES FROM "$MEASUREMENT" with KEY = "/components/component/transceiver/physical-channels/channel/@index";
EOM

echo -e "\n===== Field keys from Measurements ====="
$INFLUX <<EOM
SHOW FIELD KEYS from "$MEASUREMENT";
EOM

#echo -e "\n===== esh/state/sent ====="
#$INFLUX <<EOM
#--select "/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/packet-counters/esh/state/sent"
#--select "/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/packet-counters/iih/state/sent"
#select 
#    mean("/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/packet-counters/iih/state/dropped"), 
#    "/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/packet-counters/iih/state/processed",
#    "/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/packet-counters/iih/state/received",
#    "/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/packet-counters/iih/state/retransmit",
#    "/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/packet-counters/iih/state/sent"
#from "$MEASUREMENT"
#where "/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/@interface-id" = 'ae40.0'
#EOM

#select 
#    non_negative_derivative(mean("/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/packet-counters/iih/state/dropped")), 
#    non_negative_derivative(mean("/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/packet-counters/iih/state/processed")),
#    non_negative_derivative(mean("/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/packet-counters/iih/state/received")),
#    non_negative_derivative(mean("/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/packet-counters/iih/state/retransmit"),
#    non_negative_derivative(mean("/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/packet-counters/iih/state/sent"))
#from "/network-instances/network-instance/protocols/protocol/isis"
#where "/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/@interface-id" = 'ae40.0' and $timeFilter 
#GROUP BY time($__interval) fill(none)



#where "/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/circuit-counters/state/adj-changes" !=''
#where "/network-instances/network-instance/protocols/protocol/isis/levels/level/system-level-counters/state/auth-fails" != ''



#echo -e "\n===== interfaces ====="
#$INFLUX <<EOM
#--SHOW TAG VALUES FROM "/junos/system/linecard/interface/queue" WITH KEY = "/interfaces/interface/@name"
#SELECT "/interfaces/interface/state/counters/out-queue/@queue-number", "/interfaces/interface/state/counters/out-queue/bytes"
#FROM "/junos/system/linecard/interface/queue"
#WHERE "device"='10.161.35.118' and "/interfaces/interface/@name"='et-0/0/1' 
#GROUP BY "/interfaces/interface/state/counters/out-queue/@queue-number"
#EOM


#echo -e "\n===== Field keys from Measurements ====="
#$INFLUX <<EOM
#SHOW TAG VALUES FROM "/junos/system/linecard/interface/queue" WITH KEY = "/interfaces/interface/@name" where device = '10.161.35.118' and "/interfaces/interface/@name" =~ /^\w/;
#EOM



