#!/bin/bash

docker exec -i influxdb influx --database "telegraf" -precision "rfc3339" <<EOM

SHOW TAG VALUES FROM "qmon-sw" WITH KEY = "/junos/system/linecard/qmon-sw//@name" where device = '10.48.188.9'

-- SELECT non_negative_derivative(mean("/junos/system/linecard/qmon-sw//egress//bytes"),1s) AS "egress/bytes"
-- FROM "qmon-sw" WHERE "device"='$device' and "/junos/system/linecard/qmon-sw//@name"='$interface' and $timeFilter
-- GROUP BY "/junos/system/linecard/qmon-sw//egress//@queue-number", time($__interval) FILL(none)

EOM

