#!/bin/bash

## Image and container
export INFLUX_CONTAINER=influxdb:1.8.4
export INFLUX_PORT=8186

export TELEGRAF_CONTAINER=telegraf:1.18.1

export GRAFANA_CONTAINER=grafana/grafana:7.5.4
export GRAFANA_PORT=3300


