insecure: true
encoding: proto
log: true

targets:
  10.48.188.20:50051:
    username: regress
    password: MaRtInI
    subscriptions:
      - interface_stats
    outputs:
      - influxdb2

  10.48.188.2:50051:
    username: regress
    password: MaRtInI
    subscriptions:
      - interface_stats

subscriptions:
  interface_stats:
    paths:
      - /interfaces/interface
    stream-mode: sample
    sample-interval: 60s

outputs:
  influxdb2:
    type: influxdb
    url: http://influxdb2:8086
    #url: http://127.0.0.1:8086
    #url: http://127.0.0.1:8186
    bucket: bucket1
    #token: H-qYf7QAAzrN7l3WVw3fhOP1HtdVwunOeBa-MUZb-opFrfLfsg9REltWoyBXdUhN6Tp5LizbOWTxaaqq8LSPPw==
    org: netmon 
    batch-size: 1000
    flush-timer: 10s
  output1:
    type: file # output type
    file-type: stdout # or stderr
    format: json
