{
 "title": "/components",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "CPU Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"/components/component/properties/property/state/value\"::integer) \nFROM \"/components\" where \"/components/component/properties/property/@name\" = 'CPU Temperature'  and $timeFilter \nGROUP BY \"/components/component/@name\", time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "cpu-utilization-total",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select \"/components/component/@name\" as \"component name\",\"/components/component/properties/property/state/value\" as \"value\" from \"/components\" where \"/components/component/properties/property/@name\" = 'cpu-utilization-total'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select mean(\"/components/component/properties/property/state/value\"::integer) from \"/components\"\nwhere \"/components/component/properties/property/@name\" = 'Temperature' and $timeFilter \nGROUP BY \"/components/component/@name\", time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "cpu-utilization-total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select \"/components/component/@name\" as \"component_name\",\"/components/component/properties/property/state/value_f\" as \"value\" from \"/components\" where \"/components/component/properties/property/@name\" = 'cpu-utilization-total'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperature 2",
   "type": "table",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 17 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select \"/components/component/@name\" as \"name\", \"/components/component/properties/property/state/value\" as \"value\", \"/components/component/properties/property/state/value_f\" as \"value_f\" from \"/components\"\nwhere \"/components/component/properties/property/@name\" = 'Temperature' limit 20",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}