{
 "title": "Interfaces/interface",
 "description": "Interfaces/interface",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "device",
    "label": "Device",
    "query": "SHOW TAG VALUES FROM \"interfaces\" WITH KEY = \"device\""
   },
   {
    "name": "interface",
    "label": "Interface",
    "query": "SHOW TAG VALUES FROM \"interfaces\" WITH KEY = \"/interfaces/interface/@name\" where device = '$device'"
   }
  ]
 },
 "panels": [
  {
   "title": "$device $interface in-octets (bits/s)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(mean(\"/interfaces/interface/state/counters/in-octets\"),1s)  * 8 AS \"in-octets\" FROM \"interfaces\" WHERE \"device\"='$device' and \"/interfaces/interface/@name\"='$interface' and $timeFilter  GROUP BY time($__interval) FILL(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$device $interface out-octets (bits/s)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "interfaces",
     "query": "SELECT non_negative_derivative(mean(\"/interfaces/interface/state/counters/out-octets\"),1s)  * 8 AS \"out-octets\" FROM \"interfaces\" WHERE \"device\"='$device' and \"/interfaces/interface/@name\"='$interface' and $timeFilter  GROUP BY time($__interval) FILL(none)",
     "select": [
      [
       {
        "params": [
         "/interfaces/interface[if_name='et-0/0/51']/state/counters/if_in_octets"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "$device $interface in-octets (octets/s)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(mean(\"/interfaces/interface/state/counters/in-octets\"),1s)   AS \"in-octets\" FROM \"interfaces\" WHERE \"device\"='$device' and \"/interfaces/interface/@name\"='$interface' and $timeFilter  GROUP BY time($__interval) FILL(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$device $interface out-octets (octets/s)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "interfaces",
     "query": "SELECT non_negative_derivative(mean(\"/interfaces/interface/state/counters/out-octets\"),1s)   AS \"out-octets\" FROM \"interfaces\" WHERE \"device\"='$device' and \"/interfaces/interface/@name\"='$interface' and $timeFilter  GROUP BY time($__interval) FILL(none)",
     "select": [
      [
       {
        "params": [
         "/interfaces/interface[if_name='et-0/0/51']/state/counters/if_in_octets"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "$device $interface in-pkts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "interfaces",
     "query": "SELECT non_negative_derivative(mean(\"/interfaces/interface/state/counters/in-pkts\"),1s)   AS \"in-pkts\" FROM \"interfaces\" WHERE \"device\"='$device' and \"/interfaces/interface/@name\"='$interface' and $timeFilter  GROUP BY time($__interval) FILL(none)",
     "select": [
      [
       {
        "params": [
         "/interfaces/interface[if_name='et-0/0/51']/state/counters/if_in_octets"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "$device $interface out-pkts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "interfaces",
     "query": "SELECT non_negative_derivative(mean(\"/interfaces/interface/state/counters/out-pkts\"),1s)   AS \"out-pkts\" FROM \"interfaces\" WHERE \"device\"='$device' and \"/interfaces/interface/@name\"='$interface' and $timeFilter  GROUP BY time($__interval) FILL(none)",
     "select": [
      [
       {
        "params": [
         "/interfaces/interface[if_name='et-0/0/51']/state/counters/if_in_octets"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "$device $interface ucast/mcast/bcast",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(mean(\"/interfaces/interface/state/counters/in-broadcast-pkts\"),1s) AS \"in-broadcast-pkts\", non_negative_derivative(mean(\"/interfaces/interface/state/counters/in-multicast-pkts\"),1s) AS \"in-multicast-pkts\", non_negative_derivative(mean(\"/interfaces/interface/state/counters/in-unicast-pkts\"),1s) AS \"in-unicast-pkts\" FROM \"interfaces\" WHERE \"device\"='$device' and \"/interfaces/interface/@name\"='$interface' and $timeFilter  GROUP BY time($__interval) FILL(none)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$device $interface ucast/mcast/bcast",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(mean(\"/interfaces/interface/state/counters/out-broadcast-pkts\"),1s) AS \"out-broadcast-pkts\", non_negative_derivative(mean(\"/interfaces/interface/state/counters/out-multicast-pkts\"),1s) AS \"out-multicast-pkts\", non_negative_derivative(mean(\"/interfaces/interface/state/counters/out-unicast-pkts\"),1s) AS \"out-unicast-pkts\" FROM \"interfaces\" WHERE \"device\"='$device' and \"/interfaces/interface/@name\"='$interface' and $timeFilter  GROUP BY time($__interval) FILL(none)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "peak-buffer-occupancy",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"/interfaces/interface/state/counters/out-queue/peak-buffer-occupancy\") AS \"peak-buffer-occupancy\"\n FROM \"interfaces\" WHERE \"device\"='$device' and \"/interfaces/interface/@name\"='$interface' and $timeFilter  GROUP BY time($__interval) FILL(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "frame errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"/interfaces/interface/ethernet/state/counters/in-block-errors\") AS \"in-block-errors\", \nsum(\"/interfaces/interface/ethernet/state/counters/in-crc-errors\") AS \"in-crc-errors\",\nsum(\"/interfaces/interface/ethernet/state/counters/in-fragment-frames\") AS \"in-fragment-frames\",\nsum(\"/interfaces/interface/ethernet/state/counters/in-jabber-frames\") AS \"in-jabber-frames\",\nsum(\"/interfaces/interface/ethernet/state/counters/in-mac-control-frames\") AS \"in-mac-control-frames\",\nsum(\"/interfaces/interface/ethernet/state/counters/in-mac-pause-frames\") AS \"in-mac-pause-frames\",\nsum(\"/interfaces/interface/ethernet/state/counters/in-oversize-frames\") AS \"in-oversize-frames\"\n FROM \"interfaces\" WHERE \"device\"='$device' and \"/interfaces/interface/@name\"='$interface' and $timeFilter  GROUP BY time($__interval) FILL(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$device $interface out-queue bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(mean(\"/interfaces/interface/state/counters/out-queue/red-drop-bytes\"),1s)  AS \"red-drop-bytes\", \nnon_negative_derivative(mean(\"/interfaces/interface/state/counters/out-queue/bytes\"),1s) AS \"out-queue/bytes\"\nFROM \"interfaces\" WHERE \"device\"='$device' and \"/interfaces/interface/@name\"='$interface' and $timeFilter  GROUP BY time($__interval) FILL(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$device $interface out-queue pkts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "interfaces",
     "query": "SELECT non_negative_derivative(mean(\"/interfaces/interface/state/counters/out-queue/red-drop-pkts\"),1s) AS \"out-queue/red-drop-pkts\",\nnon_negative_derivative(mean(\"/interfaces/interface/state/counters/out-queue/pkts\"),1s) AS \"out-queue/pkts\"\nFROM \"interfaces\" WHERE \"device\"='$device' and \"/interfaces/interface/@name\"='$interface' and $timeFilter  GROUP BY time($__interval) FILL(none)",
     "select": [
      [
       {
        "params": [
         "/interfaces/interface[if_name='et-0/0/51']/state/counters/if_in_octets"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ]
    }
   ]
  }
 ]
}