{
 "title": "Interfaces",
 "time": { "from": "2021-04-21T13:02:25.329Z", "to": "2021-04-21T14:20:20.932Z" },
 "templating": {
  "list": [
   {
    "name": "device",
    "label": "Device",
    "query": "SHOW TAG VALUES FROM \"interfaces\" WITH KEY = \"device\""
   },
   {
    "name": "interface",
    "label": "Interface",
    "query": "SHOW TAG VALUES FROM \"interfaces\" WITH KEY = \"/interfaces/interface/@name\""
   }
  ]
 },
 "panels": [
  {
   "title": "$device:$interface in-octets (bps)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$interface",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "interfaces",
     "query": "select non_negative_derivative(mean(\"/interfaces/interface[if_name='$interface']/state/counters/if_in_octets\"),1s) * 8 from \"interfaces\" where \"device\" = '$device' and $timeFilter GROUP BY time($__interval) fill(none);",
     "select": [
      [
       {
        "params": [
         "/interfaces/interface[if_name='et-0/0/51']/state/counters/if_in_octets"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"value\") FROM \"measurement\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$device:$interface out-octets (bps)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$interface",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "interfaces",
     "query": "select non_negative_derivative(mean(\"/interfaces/interface[if_name='$interface']/state/counters/if_out_octets\"),1s) * 8 from \"interfaces\" where \"device\" = '$device' and $timeFilter GROUP BY time($__interval) fill(none);",
     "select": [
      [
       {
        "params": [
         "/interfaces/interface[if_name='et-0/0/51']/state/counters/if_in_octets"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"value\") FROM \"measurement\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$device:$interface error-counters",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "in_discards",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select non_negative_derivative(sum(\"/interfaces/interface[if_name='$interface']/state/error-counters/if_in_discards\"),1s)\n    from \"interfaces\" \n    where \"device\" = '$device' and $timeFilter GROUP BY time($__interval) fill(none);",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "if_in_errors",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select non_negative_derivative(sum(\"/interfaces/interface[if_name='$interface']/state/error-counters/if_in_errors\"),1s)\n    from \"interfaces\" \n    where \"device\" = '$device' and $timeFilter GROUP BY time($__interval) fill(none);",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "if_in_fifo_errors",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select non_negative_derivative(sum(\"/interfaces/interface[if_name='$interface']/state/error-counters/if_in_fifo_errors\"),1s)\n    from \"interfaces\" \n    where \"device\" = '$device' and $timeFilter GROUP BY time($__interval) fill(none);",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "if_in_frame_errors",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select non_negative_derivative(sum(\"/interfaces/interface[if_name='$interface']/state/error-counters/if_in_frame_errors\"),1s)\n    from \"interfaces\" \n    where \"device\" = '$device' and $timeFilter GROUP BY time($__interval) fill(none);",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "if_in_l2_mismatch_timeouts",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select non_negative_derivative(sum(\"/interfaces/interface[if_name='$interface']/state/error-counters/if_in_l2_mismatch_timeouts\"),1s)\n    from \"interfaces\" \n    where \"device\" = '$device' and $timeFilter GROUP BY time($__interval) fill(none);",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "if_in_l2chan_errors",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select non_negative_derivative(sum(\"/interfaces/interface[if_name='$interface']/state/error-counters/if_in_l2chan_errors\"),1s)\n    from \"interfaces\" \n    where \"device\" = '$device' and $timeFilter GROUP BY time($__interval) fill(none);",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "if_in_l3_incompletes",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select non_negative_derivative(sum(\"/interfaces/interface[if_name='$interface']/state/error-counters/if_in_l3_incompletes\"),1s)\n    from \"interfaces\" \n    where \"device\" = '$device' and $timeFilter GROUP BY time($__interval) fill(none);",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "if_in_qdrops",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select non_negative_derivative(sum(\"/interfaces/interface[if_name='$interface']/state/error-counters/if_in_qdrops\"),1s)\n    from \"interfaces\" \n    where \"device\" = '$device' and $timeFilter GROUP BY time($__interval) fill(none);",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "if_in_resource_errors",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select non_negative_derivative(sum(\"/interfaces/interface[if_name='$interface']/state/error-counters/if_in_resource_errors\"),1s)\n    from \"interfaces\" \n    where \"device\" = '$device' and $timeFilter GROUP BY time($__interval) fill(none);",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "if_in_runts",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select non_negative_derivative(sum(\"/interfaces/interface[if_name='$interface']/state/error-counters/if_in_runts\"),1s)\n    from \"interfaces\" \n    where \"device\" = '$device' and $timeFilter GROUP BY time($__interval) fill(none);",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "if_out_discards",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select non_negative_derivative(sum(\"/interfaces/interface[if_name='$interface']/state/error-counters/if_out_discards\"),1s)\n    from \"interfaces\" \n    where \"device\" = '$device' and $timeFilter GROUP BY time($__interval) fill(none);",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "if_out_errors",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select non_negative_derivative(sum(\"/interfaces/interface[if_name='$interface']/state/error-counters/if_out_errors\"),1s)\n    from \"interfaces\" \n    where \"device\" = '$device' and $timeFilter GROUP BY time($__interval) fill(none);",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}