{
 "title": "/junos/system/linecard/qmon-sw",
 "description": "/junos/system/linecard/qmon-sw",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "device_qmon_sw",
    "label": "Device",
    "query": "SHOW TAG VALUES FROM \"qmon-sw\" WITH KEY = \"device\""
   },
   {
    "name": "interface_qmon_sw",
    "label": "Interface",
    "query": "SHOW TAG VALUES FROM \"qmon-sw\" WITH KEY = \"/junos/system/linecard/qmon-sw//@name\" "
   }
  ]
 },
 "panels": [
  {
   "title": "$device_qmon_sw $interface_qmon_sw bytes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(mean(\"/junos/system/linecard/qmon-sw//egress//bytes\"),1s) AS \"egress/bytes\"\nFROM \"qmon-sw\" WHERE \"device\"='$device_qmon_sw' and \"/junos/system/linecard/qmon-sw//@name\" = '$interface_qmon_sw' and  $timeFilter\n GROUP BY \"/junos/system/linecard/qmon-sw//egress//@queue-number\", time($__interval) FILL(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$device_qmon_sw $interface_qmon_sw packets",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(mean(\"/junos/system/linecard/qmon-sw//egress//packets\"),1s) AS \"egress/packets\"\nFROM \"qmon-sw\" WHERE \"device\"='$device_qmon_sw' and \"/junos/system/linecard/qmon-sw//@name\" = '$interface_qmon_sw' and  $timeFilter\n GROUP BY \"/junos/system/linecard/qmon-sw//egress//@queue-number\", time($__interval) FILL(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$device_qmon_sw $interface_qmon_sw peak_buffer_occupancy (bps)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"/junos/system/linecard/qmon-sw//egress//peak-buffer-occupancy-bytes\") AS \"egress/peak-buffer-occupancy-bytes\"\nFROM \"qmon-sw\" WHERE \"device\"='$device_qmon_sw' and \"/junos/system/linecard/qmon-sw//@name\" = '$interface_qmon_sw' and  $timeFilter\n GROUP BY \"/junos/system/linecard/qmon-sw//egress//@queue-number\", time($__interval) FILL(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$device_qmon_sw  peak-buffer-occupancy-percent (bps)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 11, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"/junos/system/linecard/qmon-sw//egress//peak-buffer-occupancy-percent\") AS \"egress/peak-buffer-occupancy-percent\"\nFROM \"qmon-sw\" WHERE \"device\"='$device_qmon_sw' \n  and \"/junos/system/linecard/qmon-sw//@name\" = '$interface_qmon_sw' \n and  $timeFilter\n GROUP BY \"/junos/system/linecard/qmon-sw//egress//@queue-number\",  time($__interval) FILL(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$device_qmon_sw  tail-drop-bytes (bps)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"/junos/system/linecard/qmon-sw//egress//tail-drop-bytes\") AS \"egress/tail-drop-bytes\"\nFROM \"qmon-sw\" WHERE \"device\"='$device_qmon_sw' \n  and \"/junos/system/linecard/qmon-sw//@name\" = '$interface_qmon_sw' \n and  $timeFilter\n GROUP BY \"/junos/system/linecard/qmon-sw//egress//@queue-number\",  time($__interval) FILL(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$device_qmon_sw  tail-drop-packets",
   "type": "graph",
   "gridPos": { "h": 5, "w": 11, "x": 11, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"/junos/system/linecard/qmon-sw//egress//tail-drop-packets\") AS \"egress/tail-drop-packets\"\nFROM \"qmon-sw\" WHERE \"device\"='$device_qmon_sw' \n  and \"/junos/system/linecard/qmon-sw//@name\" = '$interface_qmon_sw' \n and  $timeFilter\n GROUP BY \"/junos/system/linecard/qmon-sw//egress//@queue-number\",  time($__interval) FILL(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}