{
 "title": "/junos/system/linecard/interface/queue",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "device_queue",
    "label": "Device",
    "query": "SHOW TAG VALUES FROM \"/junos/system/linecard/interface/queue\" WITH KEY = \"device\""
   },
   {
    "name": "interface_queue",
    "label": "Interface",
    "query": "SHOW TAG VALUES FROM \"/junos/system/linecard/interface/queue\" WITH KEY = \"/interfaces/interface/@name\" where device = '10.161.35.118' and \"/interfaces/interface/@name\" =~ /^\\w/"
   }
  ]
 },
 "panels": [
  {
   "title": "out queue bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "queue [[tag_/interfaces/interface/state/counters/out-queue/@queue-number]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(mean(\"/interfaces/interface/state/counters/out-queue/bytes\"),1s)\n FROM \"/junos/system/linecard/interface/queue\"\nWHERE \"device\"='$device_queue' and \"/interfaces/interface/@name\"='$interface_queue' and $timeFilter  \nGROUP BY \"/interfaces/interface/state/counters/out-queue/@queue-number\", time($__interval) FILL(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "out queue pkts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "queue [[tag_/interfaces/interface/state/counters/out-queue/@queue-number]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(mean(\"/interfaces/interface/state/counters/out-queue/pkts\"),1s)\n FROM \"/junos/system/linecard/interface/queue\"\nWHERE \"device\"='$device_queue' and \"/interfaces/interface/@name\"='$interface_queue' and $timeFilter  \nGROUP BY \"/interfaces/interface/state/counters/out-queue/@queue-number\", time($__interval) FILL(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "tail-drop-bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "queue [[tag_/interfaces/interface/state/counters/out-queue/@queue-number]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(mean(\"/interfaces/interface/state/counters/out-queue/tail-drop-bytes\"),1s)\n FROM \"/junos/system/linecard/interface/queue\"\nWHERE \"device\"='$device_queue' and \"/interfaces/interface/@name\"='$interface_queue' and $timeFilter  \nGROUP BY \"/interfaces/interface/state/counters/out-queue/@queue-number\", time($__interval) FILL(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "tail-drop-pkts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "queue [[tag_/interfaces/interface/state/counters/out-queue/@queue-number]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(mean(\"/interfaces/interface/state/counters/out-queue/tail-drop-pkts\"),1s)\n FROM \"/junos/system/linecard/interface/queue\"\nWHERE \"device\"='$device_queue' and \"/interfaces/interface/@name\"='$interface_queue' and $timeFilter  \nGROUP BY \"/interfaces/interface/state/counters/out-queue/@queue-number\", time($__interval) FILL(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}