{
 "title": "/junos/system/linecard/npu/utilization",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "device_npu_utilization",
    "label": "Device",
    "query": "SHOW TAG VALUES FROM \"/junos/system/linecard/npu/utilization\" WITH KEY = \"device\""
   }
  ]
 },
 "panels": [
  {
   "title": "util-asic-to-host-pps-rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "[[tag_/components/component/@name]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select  mean(\"/components/component/properties/property/state/value\") \nfrom \"/junos/system/linecard/npu/utilization\" \nwhere \"/components/component/properties/property/@name\" =~ /^util-asic-to-host-pps-rate/ and device = '$device_npu_utilization' and  $timeFilter \ngroup by  time($__interval), \"/components/component/@name\" fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "util-loopback-pps-rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "[[tag_/components/component/@name]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select  mean(\"/components/component/properties/property/state/value\") \nfrom \"/junos/system/linecard/npu/utilization\" \nwhere \"/components/component/properties/property/@name\" =~ /^util-loopback-pps-rate/ and device = '$device_npu_utilization' and  $timeFilter \ngroup by  time($__interval), \"/components/component/@name\" fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "util-metric",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "[[tag_/components/component/@name]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select  mean(\"/components/component/properties/property/state/value\") \nfrom \"/junos/system/linecard/npu/utilization\" \nwhere \"/components/component/properties/property/@name\" =~ /^util-metric/ and device = '$device_npu_utilization' and  $timeFilter \ngroup by  time($__interval), \"/components/component/@name\" fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "util-recirculation-pps-rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "[[tag_/components/component/@name]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select  mean(\"/components/component/properties/property/state/value\") \nfrom \"/junos/system/linecard/npu/utilization\" \nwhere \"/components/component/properties/property/@name\" =~ /^util-recirculation-pps-rate/ and device = '$device_npu_utilization' and  $timeFilter \ngroup by  time($__interval), \"/components/component/@name\" fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "util-wan-and-host-inject-pps-rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "[[tag_/components/component/@name]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select  mean(\"/components/component/properties/property/state/value\") \nfrom \"/junos/system/linecard/npu/utilization\" \nwhere \"/components/component/properties/property/@name\" =~ /^util-wan-and-host-inject-pps-rate/ and device = '$device_npu_utilization' and  $timeFilter \ngroup by  time($__interval), \"/components/component/@name\" fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}