{
 "title": "/network-instances/network-instance/protocols/protocol/bgp",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "device_bgp",
    "label": "Device",
    "query": "SHOW TAG VALUES FROM \"/network-instances/network-instance/protocols/protocol/bgp\" WITH KEY = \"device\""
   }
  ]
 },
 "panels": [
  {
   "title": "$device_bgp prefixes/received",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/@neighbor-address]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/network-instances/network-instance/protocols/protocol/bgp",
     "query": "SELECT mean(\"/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/afi-safis/afi-safi/state/prefixes/received\")\nFROM \"/network-instances/network-instance/protocols/protocol/bgp\" \nWHERE \"device\"='$device_bgp' and $timeFilter \nGROUP BY \"/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/@neighbor-address\", time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$device_bgp prefixes/sent",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/@neighbor-address]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/network-instances/network-instance/protocols/protocol/bgp",
     "query": "SELECT mean(\"/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/afi-safis/afi-safi/state/prefixes/sent\")\nFROM \"/network-instances/network-instance/protocols/protocol/bgp\" \nWHERE \"device\"='$device_bgp' and $timeFilter \nGROUP BY \"/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/@neighbor-address\", time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$device_bgp prefixes/accepted",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/@neighbor-address]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/network-instances/network-instance/protocols/protocol/bgp",
     "query": "SELECT mean(\"/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/afi-safis/afi-safi/state/prefixes/accepted\")\nFROM \"/network-instances/network-instance/protocols/protocol/bgp\" \nWHERE \"device\"='$device_bgp' and $timeFilter \nGROUP BY \"/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/@neighbor-address\", time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$device_bgp prefixes/installed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/@neighbor-address]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/network-instances/network-instance/protocols/protocol/bgp",
     "query": "SELECT mean(\"/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/afi-safis/afi-safi/state/prefixes/installed\")\nFROM \"/network-instances/network-instance/protocols/protocol/bgp\" \nWHERE \"device\"='$device_bgp' and $timeFilter \nGROUP BY \"/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/@neighbor-address\", time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$device_bgp queues/input",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/@neighbor-address]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/network-instances/network-instance/protocols/protocol/bgp",
     "query": "SELECT mean(\"/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/afi-safis/afi-safi/state/queues/input\")\nFROM \"/network-instances/network-instance/protocols/protocol/bgp\" \nWHERE \"device\"='$device_bgp' and $timeFilter \nGROUP BY \"/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/@neighbor-address\", time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$device_bgp queues/output",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/@neighbor-address]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/network-instances/network-instance/protocols/protocol/bgp",
     "query": "SELECT mean(\"/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/afi-safis/afi-safi/state/queues/output\")\nFROM \"/network-instances/network-instance/protocols/protocol/bgp\" \nWHERE \"device\"='$device_bgp' and $timeFilter \nGROUP BY \"/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/@neighbor-address\", time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}