{
 "title": "/network-instances/network-instance/protocols/protocol/isis",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "device_isis",
    "label": "Device",
    "query": "SHOW TAG VALUES FROM \"/network-instances/network-instance/protocols/protocol/isis\" WITH KEY = \"device\""
   },
   {
    "name": "interface_isis",
    "label": "Interface",
    "query": "SHOW TAG VALUES FROM \"/network-instances/network-instance/protocols/protocol/isis\" WITH KEY = \"/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/@interface-id\""
   }
  ]
 },
 "panels": [
  {
   "title": "$device_isis $interface_isis /packet-counters/csnp/state",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/network-instances/network-instance/protocols/protocol/isis",
     "query": "select \n    non_negative_derivative(mean(\"/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/packet-counters/csnp/state/dropped\")) as \"dropped\", \n    non_negative_derivative(mean(\"/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/packet-counters/csnp/state/processed\")) as \"processed\",\n    non_negative_derivative(mean(\"/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/packet-counters/csnp/state/received\")) as \"received\",\n    non_negative_derivative(mean(\"/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/packet-counters/csnp/state/retransmit\")) as \"retransmit\",\n    non_negative_derivative(mean(\"/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/packet-counters/csnp/state/sent\")) as \"sent\"\nfrom \"/network-instances/network-instance/protocols/protocol/isis\"\nwhere \"/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/@interface-id\" = '$interface_isis' and $timeFilter \nGROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$device_isis $interface_isis /packet-counters/esh/state",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/network-instances/network-instance/protocols/protocol/isis",
     "query": "select \n    non_negative_derivative(mean(\"/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/packet-counters/esh/state/dropped\")) as \"dropped\", \n    non_negative_derivative(mean(\"/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/packet-counters/esh/state/processed\")) as \"processed\",\n    non_negative_derivative(mean(\"/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/packet-counters/esh/state/received\")) as \"received\",\n    non_negative_derivative(mean(\"/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/packet-counters/esh/state/retransmit\")) as \"retransmit\",\n    non_negative_derivative(mean(\"/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/packet-counters/esh/state/sent\")) as \"sent\"\nfrom \"/network-instances/network-instance/protocols/protocol/isis\"\nwhere \"/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/@interface-id\" = '$interface_isis' and $timeFilter \nGROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$device_isis $interface_isis /packet-counters/iih/state",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/network-instances/network-instance/protocols/protocol/isis",
     "query": "select \n    non_negative_derivative(mean(\"/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/packet-counters/iih/state/dropped\")) as \"dropped\", \n    non_negative_derivative(mean(\"/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/packet-counters/iih/state/processed\")) as \"processed\",\n    non_negative_derivative(mean(\"/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/packet-counters/iih/state/received\")) as \"received\",\n    non_negative_derivative(mean(\"/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/packet-counters/iih/state/retransmit\")) as \"retransmit\",\n    non_negative_derivative(mean(\"/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/packet-counters/iih/state/sent\")) as \"sent\"\nfrom \"/network-instances/network-instance/protocols/protocol/isis\"\nwhere \"/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/@interface-id\" = '$interface_isis' and $timeFilter \nGROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$device_isis $interface_isis /packet-counters/ish/state",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/network-instances/network-instance/protocols/protocol/isis",
     "query": "select \n    non_negative_derivative(mean(\"/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/packet-counters/ish/state/dropped\")) as \"dropped\", \n    non_negative_derivative(mean(\"/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/packet-counters/ish/state/processed\")) as \"processed\",\n    non_negative_derivative(mean(\"/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/packet-counters/ish/state/received\")) as \"received\",\n    non_negative_derivative(mean(\"/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/packet-counters/ish/state/retransmit\")) as \"retransmit\",\n    non_negative_derivative(mean(\"/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/packet-counters/ish/state/sent\")) as \"sent\"\nfrom \"/network-instances/network-instance/protocols/protocol/isis\"\nwhere \"/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/@interface-id\" = '$interface_isis' and $timeFilter \nGROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$device_isis $interface_isis /packet-counters/lsp/state",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/network-instances/network-instance/protocols/protocol/isis",
     "query": "select \n    non_negative_derivative(mean(\"/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/packet-counters/lsp/state/dropped\")) as \"dropped\", \n    non_negative_derivative(mean(\"/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/packet-counters/lsp/state/processed\")) as \"processed\",\n    non_negative_derivative(mean(\"/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/packet-counters/lsp/state/received\")) as \"received\",\n    non_negative_derivative(mean(\"/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/packet-counters/lsp/state/retransmit\")) as \"retransmit\",\n    non_negative_derivative(mean(\"/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/packet-counters/lsp/state/sent\")) as \"sent\"\nfrom \"/network-instances/network-instance/protocols/protocol/isis\"\nwhere \"/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/@interface-id\" = '$interface_isis' and $timeFilter \nGROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$device_isis $interface_isis /packet-counters/psnp/state",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/network-instances/network-instance/protocols/protocol/isis",
     "query": "select \n    non_negative_derivative(mean(\"/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/packet-counters/psnp/state/dropped\")) as \"dropped\", \n    non_negative_derivative(mean(\"/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/packet-counters/psnp/state/processed\")) as \"processed\",\n    non_negative_derivative(mean(\"/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/packet-counters/psnp/state/received\")) as \"received\",\n    non_negative_derivative(mean(\"/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/packet-counters/psnp/state/retransmit\")) as \"retransmit\",\n    non_negative_derivative(mean(\"/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/packet-counters/psnp/state/sent\")) as \"sent\"\nfrom \"/network-instances/network-instance/protocols/protocol/isis\"\nwhere \"/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/@interface-id\" = '$interface_isis' and $timeFilter \nGROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$device_isis $interface_isis /packet-counters/unknown/state",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/network-instances/network-instance/protocols/protocol/isis",
     "query": "select \n    non_negative_derivative(mean(\"/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/packet-counters/unknown/state/dropped\")) as \"dropped\", \n    non_negative_derivative(mean(\"/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/packet-counters/unknown/state/processed\")) as \"processed\",\n    non_negative_derivative(mean(\"/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/packet-counters/unknown/state/received\")) as \"received\",\n    non_negative_derivative(mean(\"/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/packet-counters/unknown/state/retransmit\")) as \"retransmit\",\n    non_negative_derivative(mean(\"/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/packet-counters/unknown/state/sent\")) as \"sent\"\nfrom \"/network-instances/network-instance/protocols/protocol/isis\"\nwhere \"/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/@interface-id\" = '$interface_isis' and $timeFilter \nGROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}