#!/bin/bash

set -x

source ../params

#First, generate a sample configuration and save it as telegraf.conf on the host:
#Once youve customized telegraf.conf, you can run the Telegraf container with it mounted in the expected location:

(cd config ; cat agent.conf openconfig.conf influx.conf | envsubst > telegraf.conf )

#docker run -d --rm --name telegraf -v $PWD/telegraf.conf:/etc/telegraf/telegraf.conf:ro telegraf
docker run -d --rm --name telegraf \
        --net=container:influxdb \
	-v $PWD/config/telegraf.conf:/etc/telegraf/telegraf.conf:ro \
	$TELEGRAF_CONTAINER
