#!/bin/bash


source ../params

#docker run --rm influxdb:1.8.4-alpine influxd config > influxdb.conf

set -x

docker network create influxdb

docker run -d --rm --name influxdb \
	--net=influxdb \
       	-p $INFLUX_PORT:8086 \
       	-p $GRAFANA_PORT:3000 \
       	-v $PWD/data:/var/lib/influxdb \
       	$INFLUX_CONTAINER

# docker container stop influxdb
