#!/bin/bash

#docker run --rm influxdb:1.8.4-alpine influxd config > influxdb.conf

docker network create influxdb

docker run -d --rm --name influxdb \
	--net=influxdb \
       	-p 8086:8086 \
       	-p 2003:2003 \
       	-p 3000:3000 \
	-e INFLUXDB_GRAPHITE_ENABLED=true \
       	-v $PWD/data:/var/lib/influxdb \
       	influxdb:1.8.4

# docker container stop influxdb
